server:
  port: 8002


mybatis:
  type-aliases-package: entity
  config-location:classpath: mybatis.xml
  mapper-locations: classpath:mapper/*.xml


spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc2?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123



eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
      instance-id: springcloud-provider-dept-8002
info:
   app.name: injoker
   game.name: dota
