server:
  port: 9527

spring:
  application:
    name: springcloud-zuul-9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true

info:
  name:yzc
  game:dota
zuul:
  routes:
    my.serviceId: springcloud-provider-dept
    my.path: /my/**
  ignored-services: "*"
  prefix: /dota
